- name: Setup Frontend Component
  hosts: all
  become: true
  tasks:
    - name: Install Nginx
      ansible.builtin.dnf:
        name: nginx
        state: present
    - name: Copy ansible configuration
      ansible.builtin.copy:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf 

    - name: Setup NodeJS Repository
      ansible.builtin.shell: curl -fsSL https://rpm.nodesource.com/setup_20.x | bash -

    - name: Install NodeJS
      ansible.builtin.dnf:  
        name: nodejs
        state: present

    - name: Remove existing frontend content
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: absent

    - name: Create App  content folder
      ansible.builtin.file:
        path: /tmp/frontend
        state: directory


    - name: Download frontend content
      ansible.builtin.unarchive:
        url: https://raw.githubusercontent.com/raghudevopsb89/roboshop-microservices/main/artifacts/frontend.zip
        dest: /tmp/frontend.zip
        remote_src: yes

    - name: Build Static content
      ansible.builtin.shell: npm install && npm run build ; rm -rf /usr/share/nginx/html/* ; cp -r out/* /usr/share/nginx/html/
      args:
        chdir: /tmp/frontend

    - name: Restart Nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
        enabled: yes

        




 

